// Generated by gencpp from file kinesis_video_msgs/KinesisVideoFrame.msg
// DO NOT EDIT!


#ifndef KINESIS_VIDEO_MSGS_MESSAGE_KINESISVIDEOFRAME_H
#define KINESIS_VIDEO_MSGS_MESSAGE_KINESISVIDEOFRAME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <diagnostic_msgs/KeyValue.h>

namespace kinesis_video_msgs
{
template <class ContainerAllocator>
struct KinesisVideoFrame_
{
  typedef KinesisVideoFrame_<ContainerAllocator> Type;

  KinesisVideoFrame_()
    : index(0)
    , decoding_ts(0)
    , presentation_ts(0)
    , duration(0)
    , codec_private_data()
    , frame_data()
    , flags(0)
    , metadata()  {
    }
  KinesisVideoFrame_(const ContainerAllocator& _alloc)
    : index(0)
    , decoding_ts(0)
    , presentation_ts(0)
    , duration(0)
    , codec_private_data(_alloc)
    , frame_data(_alloc)
    , flags(0)
    , metadata(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _index_type;
  _index_type index;

   typedef uint64_t _decoding_ts_type;
  _decoding_ts_type decoding_ts;

   typedef uint64_t _presentation_ts_type;
  _presentation_ts_type presentation_ts;

   typedef uint64_t _duration_type;
  _duration_type duration;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _codec_private_data_type;
  _codec_private_data_type codec_private_data;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _frame_data_type;
  _frame_data_type frame_data;

   typedef uint16_t _flags_type;
  _flags_type flags;

   typedef std::vector< ::diagnostic_msgs::KeyValue_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::diagnostic_msgs::KeyValue_<ContainerAllocator> >::other >  _metadata_type;
  _metadata_type metadata;





  typedef boost::shared_ptr< ::kinesis_video_msgs::KinesisVideoFrame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinesis_video_msgs::KinesisVideoFrame_<ContainerAllocator> const> ConstPtr;

}; // struct KinesisVideoFrame_

typedef ::kinesis_video_msgs::KinesisVideoFrame_<std::allocator<void> > KinesisVideoFrame;

typedef boost::shared_ptr< ::kinesis_video_msgs::KinesisVideoFrame > KinesisVideoFramePtr;
typedef boost::shared_ptr< ::kinesis_video_msgs::KinesisVideoFrame const> KinesisVideoFrameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinesis_video_msgs::KinesisVideoFrame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinesis_video_msgs::KinesisVideoFrame_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kinesis_video_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'kinesis_video_msgs': ['/tmp/binarydeb/ros-kinetic-kinesis-video-msgs-2.0.2/msg'], 'diagnostic_msgs': ['/opt/ros/kinetic/share/diagnostic_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kinesis_video_msgs::KinesisVideoFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinesis_video_msgs::KinesisVideoFrame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinesis_video_msgs::KinesisVideoFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinesis_video_msgs::KinesisVideoFrame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinesis_video_msgs::KinesisVideoFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinesis_video_msgs::KinesisVideoFrame_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinesis_video_msgs::KinesisVideoFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27aa4ed7caa3f72619dd565fd09eddf0";
  }

  static const char* value(const ::kinesis_video_msgs::KinesisVideoFrame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27aa4ed7caa3f726ULL;
  static const uint64_t static_value2 = 0x19dd565fd09eddf0ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinesis_video_msgs::KinesisVideoFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinesis_video_msgs/KinesisVideoFrame";
  }

  static const char* value(const ::kinesis_video_msgs::KinesisVideoFrame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinesis_video_msgs::KinesisVideoFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# see https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/how-data.html#how-data-header-frame\n\
uint32 index\n\
\n\
uint64 decoding_ts      # in microseconds\n\
uint64 presentation_ts  # in microseconds\n\
uint64 duration         # in microseconds\n\
\n\
uint8[] codec_private_data\n\
uint8[] frame_data\n\
uint16 flags\n\
\n\
# see https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/how-meta.html\n\
diagnostic_msgs/KeyValue[] metadata\n\
\n\
================================================================================\n\
MSG: diagnostic_msgs/KeyValue\n\
string key # what to label this value when viewing\n\
string value # a value to track over time\n\
";
  }

  static const char* value(const ::kinesis_video_msgs::KinesisVideoFrame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinesis_video_msgs::KinesisVideoFrame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.decoding_ts);
      stream.next(m.presentation_ts);
      stream.next(m.duration);
      stream.next(m.codec_private_data);
      stream.next(m.frame_data);
      stream.next(m.flags);
      stream.next(m.metadata);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KinesisVideoFrame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinesis_video_msgs::KinesisVideoFrame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinesis_video_msgs::KinesisVideoFrame_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.index);
    s << indent << "decoding_ts: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.decoding_ts);
    s << indent << "presentation_ts: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.presentation_ts);
    s << indent << "duration: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.duration);
    s << indent << "codec_private_data[]" << std::endl;
    for (size_t i = 0; i < v.codec_private_data.size(); ++i)
    {
      s << indent << "  codec_private_data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.codec_private_data[i]);
    }
    s << indent << "frame_data[]" << std::endl;
    for (size_t i = 0; i < v.frame_data.size(); ++i)
    {
      s << indent << "  frame_data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.frame_data[i]);
    }
    s << indent << "flags: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.flags);
    s << indent << "metadata[]" << std::endl;
    for (size_t i = 0; i < v.metadata.size(); ++i)
    {
      s << indent << "  metadata[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::diagnostic_msgs::KeyValue_<ContainerAllocator> >::stream(s, indent + "    ", v.metadata[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINESIS_VIDEO_MSGS_MESSAGE_KINESISVIDEOFRAME_H
